// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqOPV9UUtAaE9b3qHsy4KmTuQDUV7MYBY',
    appId: '1:1080942944866:web:daf9619940c0d211fba73b',
    messagingSenderId: '1080942944866',
    projectId: 'pharmacy-39686',
    authDomain: 'pharmacy-39686.firebaseapp.com',
    storageBucket: 'pharmacy-39686.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhL1oes75D1fRuQ1R1_A4FNGRdD2oziDE',
    appId: '1:1080942944866:android:3d5997f308e1f6fdfba73b',
    messagingSenderId: '1080942944866',
    projectId: 'pharmacy-39686',
    storageBucket: 'pharmacy-39686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXzSMGhlrZBI2LYicYegXZqtVjMUEyZ-U',
    appId: '1:1080942944866:ios:2cc4ad0b234084bcfba73b',
    messagingSenderId: '1080942944866',
    projectId: 'pharmacy-39686',
    storageBucket: 'pharmacy-39686.firebasestorage.app',
    iosBundleId: 'com.app.pharmacy',
  );
}
